name: Environment

on:
  pull_request:
    branches: 
      - "main"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    # Go to https://www.rust-lang.org/tools/install
    - uses: dtolnay/rust-toolchain@stable
    # Makes CI faster by reusing rust artifacts
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "rust-dependencies"
    - name: Create venv
      run: python -m venv .env
    - name: Activate venv
      run: source .env/bin/activate
    - name: Install global dependencies
      run: .env/bin/python -m pip install -r requirements.txt
    - name: Build package
      run: |
        source .env/bin/activate
        cd transformer-scope; python -m maturin develop --release; cd ..
    - name: Install OthelloScope dependencies
      run: .env/bin/python -m pip install -r examples/othelloscope/requirements.txt
    - name: Run example
      run: .env/bin/python -m examples.othelloscope.main
    - name: Check that payload was generated
      uses: andstor/file-existence-action@v1
      with:
        files: "examples/othelloscope/output/payload"
